project_site/community/comm/board/urls.py
from . import views
from django.urls import include, path

app_name='board'
urlpatterns = [
    path('blist/', views.blist,name='blist'),                  # 게시판리스트
    path('bwrite/', views.bwrite,name='bwrite'),               # 글쓰기form
    path('bwriteOk/', views.bwriteOk,name='bwriteOk'),         # 글쓰기저장
    path('<str:b_no>/bview/', views.bview,name='bview'),       # 뷰페이지
    path('<str:b_no>/bmodify/', views.bmodify,name='bmodify'), # 수정form
    path('bmodifyOk/', views.bmodifyOk,name='bmodifyOk'),      # 수정저장
    path('<str:b_no>/bdelete/', views.bdelete,name='bdelete'), # 삭제
    path('<str:b_no>/breply/', views.breply,name='breply'),    # 답글쓰기form
    path('breplyOk/', views.breplyOk,name='breplyOk'),         # 답글쓰기저장
    # 공공데이터
    path('publicData/', views.publicData,name='publicData'),   # 공공데이터
    path('publicData2/', views.publicData2,name='publicData2'),   # 공공데이터
]

project_site/community/comm/comm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('board/', include('board.urls')),
    path('member/', include('member.urls')),
    path('blockhtml/', include('blockhtml.urls')),
] 

#파일 업로드시 url구성
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project_site/community/comm/board/models.py
from datetime import datetime
from django.db import models
from member.models import Member

# Create your models here.
class Fboard(models.Model):
    b_no = models.IntegerField(default=0,primary_key=True)
    member = models.ForeignKey(Member,on_delete=models.DO_NOTHING,null=True)
    b_title = models.CharField(max_length=1000)
    b_content = models.TextField()
    b_date = models.DateTimeField(default=datetime.now(),blank=True)
    b_group = models.IntegerField(default=0)
    b_step = models.IntegerField(default=0)
    b_indent = models.IntegerField(default=0)
    b_hit = models.IntegerField(default=1)
    b_img = models.ImageField(blank=True)
    
    def __str__(self):
        return self.b_title
    
    

project_site/community/comm/board/views.py
from django.shortcuts import redirect, render
from board.models import Fboard
from django.db.models import Q, F
from django.core.paginator import Paginator
from member.models import Member
from django.db.models import Max,Min,Avg 
import urllib # 한글인코딩
import requests # 웹스크롤링
import json
import cx_Oracle as ora
import pandas as pd

# db연결함수로 정의
def connections():
    try:
        conn= ora.connect('system/1234@localhost:1521/xe')
        # cursor = conn.cursor()
    except Exception as e:
        msg="예외발생"
        print(msg)
    return conn


#공공데이터
def publicData(request):
    nowpage = request.GET.get('nowpage',1)
    m_serviceKey ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    url = 'http://api.visitkorea.or.kr/openapi/service/rest/PhotoGalleryService/galleryList?serviceKey={}&pageNo={}&numOfRows=10&MobileOS=ETC&MobileApp=AppTest&arrange=A&_type=json'.format(m_serviceKey,nowpage)
    response = requests.get(url)
    print("views response : ",response)
    # response의 내용을 text변환
    contents = response.text
    # text를 json 타입으로 변경
    json_ob = json.loads(contents)
    # json데이터 중 필요한 데이터 가져오기
    publicData = json_ob['response']['body']['items']['item']
    print(" views bodyData : ",publicData)
    context={'publicData':publicData}
    return render(request,'publicData.html',context)

#공공데이터2
def publicData2(request):
    nowpage = request.GET.get('nowpage',1)
    m_serviceKey ='918RE13GA7OY7ZEmUzApgbOeAcQoZ%2FaHsXWcqPAKQ9YNNPj83KOstRMRIUrCFIAcm9qj2R6b7NFZjp%2FYsYzJLg%3D%3D'
    url = 'https://api.odcloud.kr/api/apnmOrg/v1/list?page={}&perPage=20&serviceKey={}'.format(nowpage,m_serviceKey)
    # url에서 정보를 받아옴.
    response = requests.get(url)
    print("views response : ",response)
    # response의 내용을 text변환
    contents = response.text
    # text를 json 타입으로 변경
    json_ob = json.loads(contents)
    # json데이터 중 필요한 데이터 가져오기
    publicData = json_ob['data']
    print(" views bodyData : ",publicData)
    context={'publicData':publicData}
    return render(request,'publicData2.html',context)

# 게시판리스트
def blist(request):
    # 현재페이지 받음, 없을때 1 고정
    nowpage = int(request.GET.get('nowpage',1))  
    conn = connections()
    query ='select * from score' 
    df = pd.read_sql_query(query,conn)
    print(df)
    
    if request.method == 'GET':
        
        # 모든 게시판 내용이 담겨있음.
        qs = Fboard.objects.all().order_by('-b_group','b_step')
        # 모든게시글을 받아서 페이지 분기 - 
        paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
        # 1,2,3 10개 blist에 담음
        blist = paginator.get_page(nowpage)
        context={'blist':blist,'nowpage':nowpage}
        return render(request,'blist.html',context) 
    else:
        category = request.POST.get('category')
        searchword = request.POST.get('searchword')
        # title검색
        if category == 'title':
            qs = Fboard.objects.filter(b_title__contains=searchword)
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
            
        elif category == 'content':    
            qs = Fboard.objects.filter(b_content__contains=searchword)
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
        
        elif category == 'all':
            # a and b
            # qs = Fboard.objects.filter(b_title__contains=searchword,b_content__contains=searchword)
            # a or b
            qs = Fboard.objects.filter(Q(b_title__contains=searchword) | Q(b_content__contains=searchword))
            # 모든게시글을 받아서 페이지 분기
            paginator = Paginator(qs,10)           # 30개 1-10,2-10,3-10
            blist = paginator.get_page(nowpage)       # paginator
            context={'blist':blist,'nowpage':nowpage,'category':category,'searchword':searchword}
            return render(request,'blist.html',context)
        

# 뷰페이지
def bview(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_hit += 1
    qs.save()
    context={'board':qs}
    return render(request,'bview.html',context)

# 수정페이지
def bmodify(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    context={'board':qs}
    return render(request,'bmodify.html',context)

# 수정페이지저장
def bmodifyOk(request):
    b_no = request.POST.get('b_no')
    b_title = request.POST.get('b_title')
    b_content = request.POST.get('b_content')
    # 파일이름 가져오기 
    b_img = request.FILES.get('b_img','')
    print("views file : ",request.FILES)
    qs = Fboard.objects.get(b_no=b_no)
    qs.b_title = b_title
    qs.b_content = b_content
    # 파일이름 저장
    qs.b_img = b_img
    qs.save()
    # Fboard.objects.create(b_id=id,b_title=title,b_content=content)
    # context = {"board":qs}
    return render(request,'bview.html',{"board":qs})
    # return redirect('board:bview')

# 게시판글쓰기
def bwrite(request):
    return render(request,'bwrite.html')

# 게시판글쓰기저장
def bwriteOk(request):
    id = request.POST.get('id')
    member = Member.objects.get(m_id=id)
    title = request.POST.get('title')
    content = request.POST.get('content')
    img = request.FILES.get('img','')
    print("views file : ",request.FILES)
    
    # b_no 수동으로 1씩증가해서 저장시켜줌.
    no = Fboard.objects.aggregate(max_b_no=Max('b_no'))
    max_no = no['max_b_no']   # b_no 최대 번호를 찾음 1.2.5. ... 26
    max_no += 1          #최고 높은 숫자를 만들어줌. 27 = no+1
    b_no = max_no
    
    qs = Fboard(b_no=b_no,member=member,b_title=title,b_content=content,b_group=b_no,b_img=img)
    qs.save()
    # Fboard.objects.create(b_id=id,b_title=title,b_content=content)
    return redirect('board:blist')

# 게시글 삭제
def bdelete(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    qs.delete()
    return redirect('board:blist')

# 답글쓰기
def breply(request,b_no):
    qs = Fboard.objects.get(b_no=b_no)
    context = {"board":qs}
    return render(request,'breply.html',context)


# 답글쓰기 저장
def breplyOk(request):
    # b_no 수동으로 1씩증가해서 저장시켜줌.
    no = Fboard.objects.aggregate(max_b_no=Max('b_no'))
    max_no = no['max_b_no']   # b_no 최대 번호를 찾음 1.2.5. ... 26
    max_no += 1          #최고 높은 숫자를 만들어줌. 27 = no+1
    b_no = max_no
    
    # 부모의 정보
    b_group = int(request.POST.get('b_group'))
    b_step = int(request.POST.get('b_step'))
    b_indent = int(request.POST.get('b_indent'))
    
    # 답글쓰기 내용
    id = request.POST.get('id')
    member = Member.objects.get(m_id=id)
    title = request.POST.get('title')
    content = request.POST.get('content')
    img = request.FILES.get('img','')
    
    # 부모의 b_group속한 게시글 b_step을 +1
    Fboard.objects.filter(b_group=b_group,b_step__gt=b_step).update(b_step=F('b_step')+1)
    
    # 부모의 bgroup,부모의 bstep+1, 부모의 b_indent+1
    qs = Fboard(b_no=b_no,member=member,b_title=title,b_content=content,b_group=b_group,b_step=b_step+1,b_indent=b_indent+1,b_img=img)
    qs.save()
    # Fboard.objects.create(b_id=id,b_title=title,b_content=content)
    return redirect('board:blist')
    
    

project_site/community/comm/board/templates/blist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>

      if('{{request.session.session_id}}'=='' || '{{request.session.session_id}}'==null){
          alert('로그인을 하셔야 접속이 가능합니다.')
          location.href="{% url 'index' %}"
      }

       function searchBtn(){
         
         if($("#searchword").val().length<=1){
           alert("검색어를 입력하셔야 검색이 가능합니다.")
           return false;
         }else{
            $("#search").submit()
         }
       }
  </script>
</head>
<body>
<section>
    <a href="{% url 'index' %}"><h1>NOTICE</h1></a>
    <div class="wrapper">
      <form action="{% url 'board:blist' %}" id="search" method="post">
        {% csrf_token %}
        {% if category %}
        <select name="category" id="category">
          <option value="all" {% if category in 'all'%}selected{% endif %} >전체</option>
          <option value="title" {% if category in 'title'%}selected{% endif %}>제목</option>
          <option value="content" {% if category in 'content'%}selected{% endif %}>내용</option>
        </select>
        {% else %}
          <select name="category" id="category">
            <option value="all">전체</option>
            <option value="title">제목</option>
            <option value="content">내용</option>
          </select>
        {% endif %}  

        <div class="title">
          {% if searchword %}
            <input type="text" id="searchword" name="searchword" size="16" value="{{searchword}}">
          {% else %}
            <input type="text" id="searchword" name="searchword" size="16">
          {% endif %}
        </div>
        <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성일</th>
        <th>작성자</th>
        <th>조회수</th>
      </tr>
      <!-- 내용부분 -->
      <tbody id="tbody">
        {% if blist %}
          {% for board in blist %}
            <tr>
              <td><span class='table-notice'>{{board.b_no}}</span></td>
              <td class='table-title' id='pInput'>
                <a href='{% url 'board:bview' board.b_no %}'>
                  {% if board.b_indent > 0  %}
                      ▶{{board.b_title}}
                  {% else %}
                    {{board.b_title}}
                  {% endif %}
                </a>
              </td> 
              <td>{{board.b_date|date:'Y-m-d H:i'}}</td>
              <td>{{board.member}}</td>
              <td>{{board.b_hit}}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspans='5'>데이터가 없습니다.</td>
          </tr>
        {% endif %}
      </tbody>
      
    </table>

    <ul class="page-num">
      <!-- 이전페이지 정리 -->
      {% if blist.has_previous %}
        <a href="?nowpage=1"><li class="first"></li></a>
        <a href="?nowpage={{blist.previous_page_number }}"><li class="prev"></li></a>
      {% else %}
        <li class="first"></li>
        <li class="prev"></li>
      {% endif %}



      <!-- 순차적 넘버링 -->
      {% for page in blist.paginator.page_range  %}
        {% if page != nowpage  %}
          <a href="?nowpage={{page}}"><li class="num off"><div>{{page}}</div></li></a>
        {% else %}
          <li class="num on"><div>{{page}}</div></li>
        {% endif %}
      {% endfor %}





      <!-- 이후 페이지 정리 -->
      {% if blist.has_next %}
        <a href="?nowpage={{ blist.next_page_number }}"><li class="next"></li></a>
        <a href="?nowpage={{blist.paginator.num_pages }}"><li class="last"></li></a>
      {% else %}
        <li class="next"></li>
        <li class="last"></li>
      {% endif %}
    </ul>

    <a href="{% url 'board:bwrite' %}"><div class="write">쓰기</div></a>
  </section>

</body>
</html>

project_site/community/comm/board/templates/bmodify.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글수정</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
      function cancelBtn(){
           location.href="{% url 'board:bview' board.b_no %}"
      }
  </script>
</head>
<body>
<section>
    <h1>게시글수정</h1>
    <hr>

    <form action="{% url 'board:bmodifyOk' %}" name="modify" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      <input type="hidden" name="b_no" value="{{board.b_no}}">
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id" value="{{board.member}}" readonly>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="b_title" value="{{board.b_title}}">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="b_content" cols="50" rows="10">{{board.b_content}}</textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="b_img" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">수정완료</button>
        <button type="button" class="cancel" onclick="cancelBtn()">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

project_site/community/comm/board/templates/breply.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>답글달기</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
</head>
<body>
<section>
    <h1>답글달기</h1>
    <hr>
    <form action="{% url 'board:breplyOk' %}" name="reply" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      <input type="hidden" name="b_no" value="{{board.b_no}}">
      <input type="hidden" name="b_group" value="{{board.b_group}}">
      <input type="hidden" name="b_step" value="{{board.b_step}}">
      <input type="hidden" name="b_indent" value="{{board.b_indent}}">
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id" value="{{request.session.session_id}}""   readonly>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title" value="<답변>{{board.b_title}} ">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
<textarea name="content" cols="50" rows="10">

---------------------------
[답글]
{{board.b_content}}
</textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="img" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">답변완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='list.do'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

project_site/community/comm/board/templates/bview.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>뷰페이지</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/read.css' %}">
  <script>
      function deleteBtn(){
         if(confirm("게시글을 삭제하시겠습니까?")){
            location.href="{% url 'board:bdelete' board.b_no %}"
         }
      }
  </script>
</head>
<body>
<section>
    <h1>NOTICE</h1>

    <table>
      <colgroup>
        <col width="80%">
        <col width="10%">
        <col width="10%">
        
      </colgroup>
      <tr>
        <th colspan="3">제목</th>
      </tr>
      <tr>
        <td colspan="3"><strong>{{board.b_title}}</strong></td>
      </tr>
      <tr>
        <td>{{board.member}}</td>
        <td>조회수</td>
        <td>{{board.b_hit}}</td>
      </tr>
      <tr>
        <td colspan="3" class="article">{{board.b_content}}</td>
      </tr>
      <tr>
        <td colspan="3"><strong>파일이름</strong></td>
      </tr>
      {% if board.b_img  %}
        <tr>
          <td colspan="3" class="article">
            <img src="{{board.b_img.url}}">        
          </td>
        </tr>
      {% endif %}
      <tr>
        <td colspan="3"><strong>다음글</strong> <span class="separator">|</span> [키즈잼] 2월 프로그램 안내</td>
      </tr>
      <tr>
        <td colspan="3"><strong>이전글</strong> <span class="separator">|</span> [키즈잼] 2020년 1분기 정기 휴관일 안내</td>
      </tr>
    </table>

    <a href="{% url 'board:blist' %}"><div class="list">목록</div></a>
    <a onclick="deleteBtn()"><div class="list">삭제</div></a>
    <a href="{% url 'board:bmodify' board.b_no %}"><div class="list">수정</div></a>
    <a href="{% url 'board:breply' board.b_no %}"><div class="list">답변달기</div></a>
  </section>
</body>
</html>

project_site/community/comm/board/templates/bwrite.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>글쓰기</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/write.css' %}">
  <script>
    if('{{request.session.session_id}}'=='' || '{{request.session.session_id}}'==null){
      alert('로그인을 하셔야 글쓰기가 가능합니다.')
      location.href="{% url 'index' %}"
    }
  </script>
</head>
<body>
<section>
    <h1>관리자 글쓰기</h1>
    <hr>

    <form action="{% url 'board:bwriteOk' %}" name="write" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <colgroup>
          <col width="15%">
          <col width="85%">
        </colgroup>
        <tr>
          <th>작성자</th>
          <td>
            <input type="text" name="id" value="{{request.session.session_id}}"   readonly>
          </td>
        </tr>
        <tr>
          <th>제목</th>
          <td>
            <input type="text" name="title">
          </td>
        </tr>
        <tr>
          <th>내용</th>
          <td>
            <textarea name="content" cols="50" rows="10"></textarea>
          </td>
        </tr>
        <tr>
          <th>이미지 표시</th>
          <td>
            <input type="file" name="img" id="file">
          </td>
        </tr>
      </table>
      <hr>
      <div class="button-wrapper">
        <button type="submit" class="write">작성완료</button>
        <button type="button" class="cancel" onclick="javascript:location.href='/board/blist'">취소</button>
      </div>
    </form>

  </section>

</body>
</html>

project_site/community/comm/board/templates/publicData.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>

  </script>
  <style>
    #img01{width:100px;}
  </style>
</head>
<body>
<section>
    <a href="{% url 'index' %}"><h1>NOTICE</h1></a>
    <div class="wrapper">
      <form action="{% url 'board:blist' %}" id="search" method="post">
        {% csrf_token %}
        {% if category %}
        <select name="category" id="category">
          <option value="all" {% if category in 'all'%}selected{% endif %} >전체</option>
          <option value="title" {% if category in 'title'%}selected{% endif %}>제목</option>
          <option value="content" {% if category in 'content'%}selected{% endif %}>내용</option>
        </select>
        {% else %}
          <select name="category" id="category">
            <option value="all">전체</option>
            <option value="title">제목</option>
            <option value="content">내용</option>
          </select>
        {% endif %}  

        <div class="title">
          {% if searchword %}
            <input type="text" id="searchword" name="searchword" size="16" value="{{searchword}}">
          {% else %}
            <input type="text" id="searchword" name="searchword" size="16">
          {% endif %}
        </div>
        <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
        <col width="40%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>제목</th>
        <th>촬영장소</th>
        <th>촬영날짜</th>
        <th>촬영자</th>
        <th>이미지경로</th>
      </tr>
      <!-- 내용부분 -->
      <tbody id="tbody">
        {% if publicData %}
          {% for pdata in publicData %}
            <tr>
              <td><span class='table-notice'>{{pdata.galTitle}}</span></td>
              <td class='table-title' id='pInput'>
                {{pdata.galPhotographyLocation}}
              </td> 
              <td>{{pdata.galCreatedtime}}</td>
              <td>{{pdata.galPhotographer}}</td>
              <td><img id="img01" src="{{pdata.galWebImageUrl}}"></td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspans='5'>데이터가 없습니다.</td>
          </tr>
        {% endif %}
      </tbody>
      
    </table>

    <ul class="page-num">
      <!-- 이전페이지 정리 -->
      {% if blist.has_previous %}
        <a href="?nowpage=1"><li class="first"></li></a>
        <a href="?nowpage={{blist.previous_page_number }}"><li class="prev"></li></a>
      {% else %}
        <li class="first"></li>
        <li class="prev"></li>
      {% endif %}



      <!-- 순차적 넘버링 -->
      <a href="?nowpage=1"><li class="num off"><div>1</div></li></a>
      <a href="?nowpage=2"><li class="num off"><div>2</div></li></a>
      <a href="?nowpage=3"><li class="num off"><div>3</div></li></a>





      <!-- 이후 페이지 정리 -->
      {% if blist.has_next %}
        <a href="?nowpage={{ blist.next_page_number }}"><li class="next"></li></a>
        <a href="?nowpage={{blist.paginator.num_pages }}"><li class="last"></li></a>
      {% else %}
        <li class="next"></li>
        <li class="last"></li>
      {% endif %}
    </ul>

    <a href="{% url 'board:bwrite' %}"><div class="write">쓰기</div></a>
  </section>

</body>
</html>