project_site/testboard/tboard/home/urls.py
from . import views
from django.urls import path

app_name=''
urlpatterns = [
    path('',views.index,name='index'),
]

project_site/testboard/tboard/stboard/urls.py
from . import views
from django.urls import path

app_name='stboard'
urlpatterns = [
    path('tpage/',views.tpage,name='tpage'),
    path('tpage2/',views.tpage2,name='tpage2'),
]

project_site/testboard/tboard/tboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stboard/', include('stboard.urls')),
    path('', include('home.urls')),

]

project_site/testboard/tboard/home/models.py
from django.db import models

# Create your models here.

project_site/testboard/tboard/stboard/models.py
from datetime import datetime
from django.db import models

# Create your models here.
class Board(models.Model):
    b_no = models.IntegerField(default=0,primary_key=True)
    member = models.CharField(max_length=1000)
    b_title = models.CharField(max_length=1000)
    b_content = models.TextField()
    b_date = models.DateTimeField(default=datetime.now(),blank=True)
    b_group = models.IntegerField(default=0)
    b_step = models.IntegerField(default=0)
    b_indent = models.IntegerField(default=0)
    b_hit = models.IntegerField(default=1)
    b_img = models.ImageField(blank=True)

    
    

project_site/testboard/tboard/home/views.py
from django.shortcuts import render

# Create your views here.
# main페이지
def index(request):
    return render(request,'index.html')

project_site/testboard/tboard/stboard/views.py
from django.shortcuts import render
import cx_Oracle as ora
import pandas as pd
from stboard.models import Board

# db연결함수로 정의
def connections():
    try:
        conn= ora.connect('system/1234@localhost:1521/xe')
        # cursor = conn.cursor()
    except Exception as e:
        msg="예외발생"
        print(msg)
    return conn


# tpage board게시판리스트
def tpage(request):
    ## import cx_Oracle as ora
    ## 오라클 연결
    df = pd.read_excel('C:/pyFolder/js_work/board_code.xlsx',usecols='A:D',dtype={0:int,1:str,2:str,3:str})
    # df1 = df[['bid','btitle','bname','bgroup']]
    rows=[ ]
    for x in df.to_records(index=False):
        row=[ int(x[0]),x[1],x[2],x[3] ]
        rows.append(row)
    
    conn = connections()
    print(conn.version) # 18.4.0.0.0 
    cursor = conn.cursor()   
    print(cursor) # <cx_Oracle.Cursor on <cx_Oracle.Connection to c##ora_user1@localhost:1521/xe>>
    
    # oracle db 에 저장
    cursor.execute('delete from board')
    board_query = 'insert into board(bid,btitle,bname,bgroup) values(:1,:2,:3,:4)'
    cursor.executemany(board_query,rows)
    conn.commit()
    
    cursor.execute('select count(*) from board')
    cnt = cursor.fetchone()
    print('insert 건수 : ',cnt)
    
    cursor.close()
    conn.close()
    return render(request,'blist.html')



# tpage board게시파리스트2
def tpage2(request):
    # conn = connections()
    # query ='select * from score' 
    # df = pd.read_sql_query(query,conn)
    # print(df)
    # df.to_sql('score2',con=connections(), if_exists='append', chunksize=1000, index=False, method='multi')
    # conn.close()  
    bid=1
    qs = Board.objects.all()
    print(qs.query)
    context={'blist':qs}
    
    return render(request,'blist2.html',context)

project_site/testboard/tboard/home/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>메인페이지</h2>
       <ul>
           <li><a href="{% url 'stboard:tpage' %}">oracle 저장리스트</a></li>
           <li><a href="{% url 'stboard:tpage2' %}">oracle 저장된것 읽기리스트</a></li>
       </ul>
    
</body>
</html>

project_site/testboard/tboard/stboard/templates/blist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>


  </script>
</head>
<body>
<section>
    <a href="""><h1>NOTICE</h1></a>
    <div class="wrapper">
      <form action="" id="search" method="post">
        {% csrf_token %}
        <select name="category" id="category">
          <option value="all"  >전체</option>
          <option value="title" >제목</option>
          <option value="content" >내용</option>
        </select>
       

        <div class="title">
            <input type="text" id="searchword" name="searchword" size="16">
        </div>
        <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성일</th>
        <th>작성자</th>
        <th>조회수</th>
      </tr>
      <!-- 내용부분 -->
      <tbody id="tbody">
            <tr>
              <td><span class='table-notice'>1</span></td>
              <td class='table-title' id='pInput'>
                <a href=''>제목
                </a>
              </td> 
              <td>일자</td>
              <td>아이디</td>
              <td>1</td>
            </tr>
       
      </tbody>
      
    </table>

    <ul class="page-num">
      <!-- 이전페이지 정리 -->
        <li class="first"></li>
        <li class="prev"></li>



      <!-- 순차적 넘버링 -->
          <li class="num on"><div></div></li>


      <!-- 이후 페이지 정리 -->
        <li class="next"></li>
        <li class="last"></li>
    </ul>

    <a href=""><div class="write">쓰기</div></a>
  </section>

</body>
</html>

project_site/testboard/tboard/stboard/templates/blist2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>게시판</title>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:400,500,700,900&display=swap&subset=korean" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/notice_list.css' %}">
  <script>

  </script>
</head>
<body>
<section>
    <a href="{% url 'index' %}"><h1>NOTICE</h1></a>
    <div class="wrapper">
      <form action="#" id="search" method="post">
        {% csrf_token %}
          <select name="category" id="category">
            <option value="all">전체</option>
            <option value="title">제목</option>
            <option value="content">내용</option>
          </select>

        <div class="title">
            <input type="text" id="searchword" name="searchword" size="16">
        </div>
        <button type="button" onclick="searchBtn()"><i class="fas fa-search"></i></button>
      </form>
    </div>

    <table>
      <colgroup>
        <col width="15%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
        <col width="15%">
      </colgroup>
      <!-- 제목부분 -->
      <tr>
        <th>No.</th>
        <th>제목</th>
        <th>작성일</th>
        <th>작성자</th>
        <th>조회수</th>
      </tr>
      <!-- 내용부분 -->
      <tbody id="tbody">
        {% if blist %}
          {% for board in blist %}
            <tr>
              <td><span class='table-notice'>{{board.b_no}}</span></td>
              <td class='table-title' id='pInput'>
                <a href='#'>
                  {% if board.b_indent > 0  %}
                  {% for i in "x"|rjust:board.b_indent %}
                    ▶
                  {% endfor %}
                    {{board.b_title}}
                  {% else %}
                    {{board.b_title}}
                  {% endif %}
                </a>
              </td> 
              <td>{{board.b_date|date:'Y-m-d H:i'}}</td>
              <td>{{board.member}}</td>
              <td>{{board.b_hit}}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspans='5'>데이터가 없습니다.</td>
          </tr>
        {% endif %}
      </tbody>
      
    </table>

    <ul class="page-num">
      <!-- 이전페이지 정리 -->
        <li class="first"></li>
        <li class="prev"></li>


      <!-- 순차적 넘버링 -->
          <li class="num on"><div>1</div></li>

      <!-- 이후 페이지 정리 -->
        <li class="next"></li>
        <li class="last"></li>
    </ul>

    <a href="#"><div class="write">쓰기</div></a>
  </section>

</body>
</html>