project_site/community/comm/blockhtml/urls.py
from . import views
from django.urls import include, path

app_name='blockhtml'
urlpatterns = [
    path('main/', views.main,name='main'),
    path('ora_list/', views.ora_list,name='ora_list'),
    path('notice_list/', views.notice_list,name='notice_list'),
    path('notice_read/', views.notice_read,name='notice_read'),
    
]

project_site/community/comm/board/urls.py
from . import views
from django.urls import include, path

app_name='board'
urlpatterns = [
    path('blist/', views.blist,name='blist'),                  # 게시판리스트
    path('bwrite/', views.bwrite,name='bwrite'),               # 글쓰기form
    path('bwriteOk/', views.bwriteOk,name='bwriteOk'),         # 글쓰기저장
    path('<str:b_no>/bview/', views.bview,name='bview'),       # 뷰페이지
    path('<str:b_no>/bmodify/', views.bmodify,name='bmodify'), # 수정form
    path('bmodifyOk/', views.bmodifyOk,name='bmodifyOk'),      # 수정저장
    path('<str:b_no>/bdelete/', views.bdelete,name='bdelete'), # 삭제
    path('<str:b_no>/breply/', views.breply,name='breply'),    # 답글쓰기form
    path('breplyOk/', views.breplyOk,name='breplyOk'),         # 답글쓰기저장
    # 공공데이터
    path('publicData/', views.publicData,name='publicData'),   # 공공데이터
    path('publicData2/', views.publicData2,name='publicData2'),   # 공공데이터
]

project_site/community/comm/comm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('board/', include('board.urls')),
    path('member/', include('member.urls')),
    path('blockhtml/', include('blockhtml.urls')),
] 

#파일 업로드시 url구성
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project_site/community/comm/home/urls.py
from . import views
from django.urls import include, path

app_name=''
urlpatterns = [
    path('', views.index,name='index'),
]

project_site/community/comm/member/urls.py
from . import views
from django.urls import include, path

app_name='member'
urlpatterns = [
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
]

project_site/community/comm/home/views.py
from django.shortcuts import render

# main페이지
def index(request):
    return render(request,'index.html')

project_site/community/comm/home/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>메인페이지</h2>
    {% if request.session.session_id %}
       <p>{{request.session.session_id}}님 환영합니다.</p>
       <ul>
           <li><a href="{% url 'blockhtml:ora_list' %}">oracle 저장리스트</a></li>
           <li><a href="{% url 'board:blist' %}">게시판리스트</a></li>
           <li><a href="{% url 'board:publicData' %}">공공데이터</a></li>
           <li><a href="{% url 'board:publicData2' %}">공공데이터2</a></li>
           <li><a href="{% url 'blockhtml:main' %}">block메인</a></li>
           <li><a href="{% url 'blockhtml:notice_list' %}">block게시판</a></li>
           <li><a href="{% url 'blockhtml:notice_read' %}">block뷰</a></li>
           <li><a href="/admin">관리자페이지</a></li>
           <li><a href="{% url 'member:logout' %}">로그아웃</a></li>
           <li>회원정보리스트</li>
       </ul>
       {% else %}
       <p>로그인을 하셔야 합니다.</p>   
       <ul>
           <li><a href="{% url 'member:login' %}">로그인</a></li>
       </ul>
    {% endif %}
    
</body>
</html>